name: CI

on: [push, pull_request]

jobs:
  rubies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-head, '3.2', '3.1', '3.0', '2.7', truffleruby ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run test
        run: rake
      - name: Install gem
        run: rake install
  platforms:
    strategy:
      matrix:
        os: [macos]
        ruby: ['3.0']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run test
        run: rake
      - name: Install gem
        run: rake install
